mode: chatops
branchName: '${issue.number}-${issue.title,}'
gitSafeReplacementChar: '-'
defaultBranch: develop
branches:
  - label: enhancement
    prefix: feature/
  - label: bug
    prefix: bugfix/
